#!/usr/bin/env python3
"""
Convert JSON cookies (from browser extensions) to Netscape format for yt-dlp.
"""

import json
import sys
from datetime import datetime

def json_to_netscape(json_file, netscape_file):
    """Convert JSON cookies to Netscape format."""
    try:
        with open(json_file, 'r', encoding='utf-8') as f:
            cookies = json.load(f)
    except Exception as e:
        print(f"Error reading JSON file: {e}")
        return False
    
    # Netscape cookie file header
    netscape_content = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by convert_cookies.py",
        "# Generated: " + datetime.now().isoformat(),
        ""
    ]
    
    for cookie in cookies:
        # Extract fields
        domain = cookie.get('domain', '')
        # Remove leading dot if present (Netscape format uses it differently)
        if domain.startswith('.'):
            domain_flag = 'TRUE'
            domain = domain[1:]  # Remove leading dot
        else:
            domain_flag = 'FALSE'
        
        path = cookie.get('path', '/')
        secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
        expiration = cookie.get('expirationDate', 0)
        if expiration == 0:
            expiration = '0'  # Session cookie
        else:
            expiration = str(int(expiration))
        
        name = cookie.get('name', '')
        value = cookie.get('value', '')
        
        # Netscape format: domain, domain_flag, path, secure, expiration, name, value
        # Tab-separated
        line = '\t'.join([
            domain,
            domain_flag,
            path,
            secure,
            expiration,
            name,
            value
        ])
        netscape_content.append(line)
    
    # Write Netscape format file
    try:
        with open(netscape_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(netscape_content))
        print(f"Successfully converted {len(cookies)} cookies")
        print(f"Saved to: {netscape_file}")
        return True
    except Exception as e:
        print(f"Error writing Netscape file: {e}")
        return False

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python convert_cookies.py <json_cookie_file> [netscape_output_file]")
        print("\nExample:")
        print("  python convert_cookies.py cookies.json cookies_netscape.txt")
        sys.exit(1)
    
    json_file = sys.argv[1]
    if len(sys.argv) >= 3:
        netscape_file = sys.argv[2]
    else:
        netscape_file = json_file.replace('.json', '_netscape.txt').replace('.txt', '_netscape.txt')
    
    if json_to_netscape(json_file, netscape_file):
        print("\nConversion complete!")
        print(f"\nNext steps:")
        print(f"1. Upload '{netscape_file}' to S3:")
        print(f"   aws s3 cp \"{netscape_file}\" s3://elasticbeanstalk-ap-south-1-130236498315/yt_cookie.txt")
        print(f"2. Or update YTDLP_COOKIES_S3_KEY to point to the new file name")
    else:
        sys.exit(1)
